[project]
name = "test-for-ufo2ft-issue-988"
version = "0.1.0"
description = "Testing the impact of ufo2ft issue #988"
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.14"
dependencies = [
    "fonttools>=4.63.0",
    "tqdm>=4.68.3",
    "ufo2ft>=3.8.1",
    "ufolib2>=0.18.1",
    "uharfbuzz>=0.55.0",
]

[dependency-groups]
dev = []
